'use strict';
const assert = require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {makeDOM}=require('./quest-dom.cjs');
const code=fs.readFileSync('assets/admin/admin.js','utf8'),html=fs.readFileSync('admin.html','utf8');
const settle=async()=>{for(let i=0;i<6;i++)await new Promise(r=>setImmediate(r));};
function harness(options={}) {
 const document=makeDOM(html),calls=[],events={},timers=[];let authHandler;
 const proto=Object.getPrototypeOf(document.body);
 proto.remove=function(){if(this.parentElement){this.parentElement.childNodes=this.parentElement.childNodes.filter(x=>x!==this);this.parentElement=null;}};
 proto.checkValidity=function(){return /^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(this.value);};proto.reportValidity=function(){return this.checkValidity();};
 document.getElementById=id=>document.querySelector('#'+id);document.createTextNode=value=>{const n=document.createElement('span');n.textContent=value;return n;};document.addEventListener=(event,fn)=>events['document:'+event]=fn;
 const $=id=>document.getElementById(id);$('game-filter').value='';
 let list=options.list||[{id:'00000000-0000-4000-8000-000000000001',game_id:'addition_game',body:'<img src=x onerror=alert(1)> test',status:'pending',created_on:'2026-10-08'}];
 let session=options.session===undefined?{user:{id:'admin'}}:options.session;
 const auth={initialize:async()=>({error:options.initializationError}),getSession:async()=>({data:{session},error:options.sessionError}),getUser:async()=>({data:{user:{id:session?.user.id,email:'admin@example.test'}}}),onAuthStateChange:fn=>{authHandler=fn;return {data:{subscription:{unsubscribe(){}}}};},signOut:async()=>{calls.push({method:'signout'});session=null;authHandler?.('SIGNED_OUT',null);return {error:options.signOutError};},signInWithOtp:async args=>{calls.push({method:'signin',args});return options.signin?options.signin(args):{error:options.signInError};},stopAutoRefresh(){}};
 const rpc=async(name,args)=>{calls.push({method:name,args});if(options.rpc)return options.rpc(name,args);if(name==='review_admin_status')return {data:options.admin!==false};if(name==='review_admin_set_status'){list=list.map(r=>r.id===args.p_id?{...r,status:args.p_status}:r);return {data:{id:args.p_id,status:args.p_status}};}const items=list.filter(r=>(!args.p_status||args.p_status===r.status)&&(!args.p_game_id||args.p_game_id===r.game_id));return {data:{items:items.slice(args.p_offset,args.p_offset+args.p_limit),total:items.length,counts:{pending:list.filter(x=>x.status==='pending').length,approved:list.filter(x=>x.status==='approved').length,rejected:list.filter(x=>x.status==='rejected').length,all:list.length}}};};
 const storage=new Map();const context={document,console,URL,Error,Map,Object,Number,String,Boolean,setTimeout:(fn,ms)=>{if(ms<100)setImmediate(fn);else timers.push(fn);return timers.length;},clearTimeout(){},KRIS_ADMIN_CONFIG:{url:'https://oxzudyliysixpflfxsye.supabase.co',publishableKey:'sb_publishable_test'},KRIS_ADMIN_GAMES:[{id:'addition_game',name:'加法果园',href:'./addition_game.html'}],supabase:{createClient:(url,key,opts)=>{calls.push({method:'client',opts});return {auth,rpc};}},location:{href:'https://caozixiong.github.io/kris/admin.html',reload:()=>calls.push({method:'reload'})},sessionStorage:{getItem:key=>storage.get(key),setItem:(key,value)=>storage.set(key,value),removeItem:key=>storage.delete(key)},addEventListener:(event,fn)=>events[event]=fn};context.window=context;
 vm.runInNewContext(code,context);
 return {$,document,calls,events,timers,storage,authEvent:(event,s)=>authHandler(event,s)};
}
(async()=>{
 const loggedOut=harness({session:null});await settle();assert.equal(loggedOut.$('workspace').hidden,true);assert.equal(loggedOut.$('login').hidden,false);assert.equal(loggedOut.calls.filter(c=>c.method.startsWith('review_admin')).length,0);
 loggedOut.$('email').value='admin@example.test';loggedOut.$('login-form').dispatch('submit');loggedOut.$('login-form').dispatch('submit');await settle();const signins=loggedOut.calls.filter(c=>c.method==='signin');assert.equal(signins.length,1);assert.equal(signins[0].args.options.shouldCreateUser,false);assert.equal(signins[0].args.options.emailRedirectTo,'https://caozixiong.github.io/kris/admin.html');assert.equal(loggedOut.$('send-link').disabled,true);loggedOut.timers[0]();assert.equal(loggedOut.$('send-link').disabled,false);
 loggedOut.authEvent('SIGNED_IN',{user:{id:'other-tab'}});await settle();assert.equal(loggedOut.calls.filter(c=>c.method==='signout').length,0);assert.equal(loggedOut.$('login').hidden,false);
 const expired=harness({session:null,initializationError:{code:'otp_expired'}});await settle();assert.match(expired.$('notice').textContent,/登录链接已失效/);
 const denied=harness({admin:false});await settle();assert.equal(denied.$('workspace').hidden,true);assert.equal(denied.$('denied').hidden,false);assert.equal(denied.calls.filter(c=>c.method==='review_admin_list').length,0);
 const h=harness();await settle();assert.equal(h.$('workspace').hidden,false);assert.equal(h.$('review-list').children.length,1);assert.equal(h.$('review-list').querySelector('img'),null);assert.match(h.$('review-list').textContent,/<img/);assert.equal(h.calls[0].opts.auth.storageKey,'kris-review-admin-session');
 h.$('review-list').querySelector('.primary').click();assert.equal(h.calls.filter(c=>c.method==='review_admin_set_status').length,0);assert.ok(h.$('review-list').querySelector('.confirm-action'));h.$('review-list').querySelector('.confirm-action .quiet').click();assert.equal(h.$('review-list').querySelector('.confirm-action'),null);
 h.$('review-list').querySelector('.primary').click();h.$('review-list').querySelector('.confirm-action .primary').click();h.$('review-list').querySelector('.confirm-action .primary').click();await settle();assert.equal(h.calls.filter(c=>c.method==='review_admin_set_status').length,1);assert.equal(h.$('review-list').children.length,0);assert.match(h.$('notice').textContent,/已通过/);
 h.document.querySelector('[data-status="all"]').click();await settle();assert.equal(h.$('review-list').children.length,1);assert.ok(h.$('review-list').querySelector('.badge.approved'));h.$('review-list').querySelector('.reject').click();h.$('review-list').querySelector('.confirm-action .primary').click();await settle();assert.ok(h.$('review-list').querySelector('.badge.rejected'));
 h.$('logout').click();await settle();assert.equal(h.$('workspace').hidden,true);assert.equal(h.$('review-list').children.length,0);assert.equal(h.$('account-label').textContent,'');
 const fail=harness({rpc:async(name)=>name==='review_admin_status'?{data:true}:{error:{code:'42501'}}});await settle();assert.equal(fail.$('workspace').hidden,true);assert.equal(fail.$('review-list').children.length,0);
 const stale=harness({rpc:async(name)=>name==='review_admin_status'?{data:true}:name==='review_admin_set_status'?{error:{code:'40001'}}:{data:{items:[{id:'r',game_id:'addition_game',body:'text',status:'pending',created_on:'2026-10-08'}],total:1}}});await settle();stale.$('review-list').querySelector('.primary').click();stale.$('review-list').querySelector('.confirm-action .primary').click();await settle();assert.match(stale.$('notice').textContent,/刚刚被改/);assert.equal(stale.calls.filter(c=>c.method==='review_admin_set_status').length,1);assert.equal(stale.calls.filter(c=>c.method==='review_admin_list').length,2);
 let resolveList;const delayed=harness({rpc:async(name)=>name==='review_admin_status'?{data:true}:new Promise(r=>resolveList=r)});await settle();delayed.$('logout').click();await settle();resolveList({data:{items:[{id:'r',game_id:'addition_game',body:'private',status:'pending'}],total:1}});await settle();assert.equal(delayed.$('review-list').children.length,0);assert.equal(delayed.$('workspace').hidden,true);
 const offline=harness({signOutError:{message:'offline'}});await settle();offline.$('logout').click();await settle();assert.equal(offline.$('workspace').hidden,true);assert.match(offline.$('notice').textContent,/未能确认服务器退出/);offline.authEvent('SIGNED_IN',{user:{id:'admin'}});await settle();assert.equal(offline.$('workspace').hidden,true);
 const page=harness();await settle();page.events.pagehide();assert.equal(page.$('review-list').children.length,0);page.events.pageshow({persisted:true});assert.ok(page.calls.some(c=>c.method==='reload'));
 console.log('PASS: actual admin script DOM behavior: signed-out/nonadmin lock, no signup, email resend cooldown, XSS text rendering, confirmed-only status actions, duplicate clicks, filters/reversible states, server-denied lock, conflict reload, logout during pending read, offline logout, pagehide and back/forward cache.');
})().catch(error=>{console.error(error);process.exit(1);});
