"""Validate and build the offline beginner Chinese bank.

Run: python tools/build_chinese_bank.py [--check]
The canonical editorial source is data/chinese-bank.json. No network required.
"""
from collections import Counter
import json
from pathlib import Path
import re
import sys
import unicodedata

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data/chinese-bank.json"
TARGET = ROOT / "assets/chinese-bank.js"
TONES = "āáǎàēéěèīíǐìōóǒòūúǔùǖǘǚǜ"


def validate(data):
    assert data["version"] == 1
    entries = data["entries"]
    themes = data["themes"]
    assert len(entries) == 300, "Exactly 300 learning entries are required"
    assert len({e["hanzi"] for e in entries}) == 300, "Duplicate written entry"
    assert [e["id"] for e in entries] == [f"zh{i:03}" for i in range(1, 301)]
    assert len(themes) == len({t["id"] for t in themes}) == 15
    theme_ids = {t["id"] for t in themes}
    for theme in themes:
        assert re.fullmatch(r"[a-z]+", theme["id"])
        assert all(isinstance(theme[k], str) and theme[k].strip() for k in ("zh", "en", "fr"))
    assert Counter(e["theme"] for e in entries) == {t: 20 for t in theme_ids}
    for item in entries + data["buildingTargets"]:
        for key in ("id", "hanzi", "pinyin", "en", "fr", "theme"):
            assert isinstance(item[key], str) and item[key].strip(), (item["id"], key)
            assert item[key] == unicodedata.normalize("NFC", item[key]), item["id"]
        assert re.fullmatch(r"[\u4e00-\u9fff]{1,4}", item["hanzi"]), item["id"]
        assert item["theme"] in theme_ids
        assert isinstance(item["cue"], str)
        assert not re.search(r"[<>]|https?://", item["cue"])
        syllables = item["pinyin"].split(" ")
        assert len(syllables) == len(item["hanzi"]), item["id"]
        assert any(c in TONES for c in item["pinyin"]), item["id"]
        for syllable in syllables:
            assert re.fullmatch(r"[a-zü" + TONES + r"]+", syllable), item["id"]
            assert sum(c in TONES for c in syllable) <= 1, item["id"]
        if item.get("picture"):
            assert re.fullmatch(r"[a-z]+", item["picture"])
            assert (ROOT / "assets/learning-pictures" / (item["picture"] + ".svg")).is_file()
    assert all(e["level"] in (1, 2, 3) for e in entries)
    assert all(e["level"] == 1 for e in entries[:20])
    lookup = {e["id"]: e for e in entries}
    targets = data["buildingTargets"]
    assert len(targets) == len({t["id"] for t in targets}) == len({t["hanzi"] for t in targets}) == 20
    for target in targets:
        assert target["kind"] in ("noun", "phrase")
        assert 2 <= len(target["parts"]) <= 3
        parts = [lookup[p] for p in target["parts"]]
        assert all(int(p["id"][2:]) <= 100 for p in parts)
        assert all(len(p["hanzi"]) == 1 for p in parts)
        assert "".join(p["hanzi"] for p in parts) == target["hanzi"]
        # A natural compound can neutralize a component tone: 人 rén → 大人 dà ren.
        expected_pinyin = {"大人": "dà ren"}.get(
            target["hanzi"], " ".join(p["pinyin"] for p in parts)
        )
        assert expected_pinyin == target["pinyin"]


def main():
    if any(arg != "--check" for arg in sys.argv[1:]):
        raise SystemExit("Usage: python tools/build_chinese_bank.py [--check]")
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    validate(data)
    payload = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    content = (
        "/* GENERATED by tools/build_chinese_bank.py. Edit data/chinese-bank.json. */\n"
        "(function (root, factory) {\n"
        "  'use strict';\n"
        "  const bank = factory();\n"
        "  if (typeof module === 'object' && module.exports) module.exports = bank;\n"
        "  if (root) root.KrisChineseBank = bank;\n"
        "})(typeof window !== 'undefined' ? window : typeof globalThis !== 'undefined' ? globalThis : this, function () {\n"
        "  'use strict';\n"
        "  return " + payload + ";\n"
        "});\n"
    )
    if "--check" in sys.argv:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != content:
            raise SystemExit("chinese-bank.js is stale: run python tools/build_chinese_bank.py")
        print("Chinese bank asset is current: 300 entries, 15 themes, 20 separate building targets.")
    else:
        TARGET.write_text(content, encoding="utf-8")
        print("Built assets/chinese-bank.js: 300 entries, 15 themes, 20 separate building targets.")


if __name__ == "__main__":
    main()
