"""Build the synchronous offline-friendly browser asset from the canonical JSON.
Run python tools/build_word_bank.py [--check]. Requires Python 3 and Node 18+. No network or third-party dependencies.
"""
from pathlib import Path
import json, sys, subprocess
ROOT = Path(__file__).resolve().parents[1]
source = ROOT / 'data/word-bank.json'
data = json.loads(source.read_text())
assert data['version'] == 1
assert len(data['words']) == 500
assert len({w['id'] for w in data['words']}) == 500
assert len({t['id'] for t in data['topics']}) == len(data['topics'])
for w in data['words']:
    assert all(isinstance(w[k], str) and w[k].strip() for k in ['id','theme','en','fr','lemmaEn','lemmaFr','zh','pos'])
    assert w['level'] in (1,2,3)
    assert w['theme'] in {t['id'] for t in data['topics']}
    assert w['gender'] in ('m','f',None)
    assert (w['pos'] == 'noun') == (w['gender'] is not None), w['id']
    assert w['pos'] == 'noun' or w['article'] is None
for t in data['topics']:
    assert len([w for w in data['words'] if w['theme'] == t['id']]) >= 8
    assert all(t['labels'][lang] for lang in ['zh','en','fr'])
header = '/* GENERATED by tools/build_word_bank.py. Edit data/word-bank.json, not this file. */\n'
payload = json.dumps(data, ensure_ascii=False, separators=(',', ':'))
runtime = (ROOT / 'tools/word-bank-runtime.js').read_text()
result = header + "(function (root) {\n  'use strict';\n  const source = " + payload + ";\n" + runtime + "\n})(typeof window === 'undefined' ? globalThis : window);\n"
target = ROOT / 'assets/word-bank.js'
if '--check' in sys.argv:
    if not target.exists() or target.read_text() != result:
        raise SystemExit('word-bank.js is stale: run python tools/build_word_bank.py')
    print('Word bank generated asset is current: 500 entries.')
else:
    target.write_text(result)
    print('Built assets/word-bank.js: 500 entries.')

# The compact fallback is generated from exactly the same reviewed source.
# Keep the original IDs so existing saved challenges and tests stay valid.
fallback_ids = {
    'animals': ['cat','dog','rabbit','bird','fish','horse','cow','duck'],
    'food': ['apple','banana','orange','carrot','tomato','egg','strawberry','cake'],
    'school': ['book','pencil','pen','notebook','ruler','eraser','schoolbag','chair'],
    'nature': ['tree','flower','leaf','mountain','river','cloud','star','rainbow']
}
word_data = ROOT / 'assets/word-data.js'
if word_data.exists():
    text = word_data.read_text()
    start_marker = '  // BEGIN GENERATED WORD BANK FALLBACK'
    end_marker = '  // END GENERATED WORD BANK FALLBACK'
    assert text.count(start_marker) == 1 and text.count(end_marker) == 1, 'Missing fallback generation markers'
    # Use the generated runtime for its localized hints as well as its data.
    script = "const b=require(process.argv[1]); const ids=JSON.parse(process.argv[2]); console.log(JSON.stringify(Object.entries(ids).map(([theme,keys])=>{const t=b.topics.find(t=>t.id===theme); return {...t,items:keys.map(key=>b.get('word_'+theme+'_'+key))};})));"
    fallback = json.loads(subprocess.check_output(['node','-e',script,str(target),json.dumps(fallback_ids)],text=True))
    assert sum(len(t['items']) for t in fallback) == 32
    assert all(item for topic in fallback for item in topic['items'])
    replacement = start_marker + '\n  const wordTopics = ' + json.dumps(fallback,ensure_ascii=False,indent=2).replace('\n','\n  ') + ';\n' + end_marker
    begin = text.index(start_marker); end = text.index(end_marker) + len(end_marker)
    updated = text[:begin] + replacement + text[end:]
    if '--check' in sys.argv:
        if updated != text:
            raise SystemExit('word-data.js fallback is stale: run python tools/build_word_bank.py')
        print('Generated fallback matches all 32 canonical entries and topic hints.')
    else:
        word_data.write_text(updated)
        print('Regenerated word-data.js fallback from 32 canonical entries.')
